### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by seqryan** [dbpedia/embeddings#2]
File "WikiDetector.py", line 132, in <module>
    surfForms = loadSurfaceForms("AnchorDictionary.csv", 5)#selecting the top 5 most common anchor text
  File "WikiDetector.py", line 90, in loadSurfaceForms
    with open(filename, 'r') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'AnchorDictionary.csv'

How do I generate this file?

**Comment by bharat-suri** [comment]
You need to create the dictionary containing all the surface forms with [this](https://github.com/tramplingWillow/embeddings/blob/master/gsoc2017-akshay/MakeDictionary.py)
