### ISSUE TITLE
Broken Link to the embeddings 

### ISSUE THREAD

**Issue by nooralahzadeh** [dbpedia/embeddings#4]
The link to the repository which has the embeddings and the dbpedia instances does not work

**Comment by mommi84** [comment]
Hi @nooralahzadeh! If you mean the "DBpedia 1 million" dataset, please note:

> You can download the 1 million DBpedia dataset for training, and the final DistMult embeddings from <a href="http://tsoru.aksw.org/DBp1m/">here</a> (please try refreshing the link if it is not working).

These however are not the embeddings of the whole DBpedia knowledge base. We are working on them in a project for the Google Summer of Code 2018.

**Comment by reeshabhranjan** [comment]
Is this issue fixed?
